Timetable period changes
Klartopedia/erp-api pull request #608
Opened 2023-11-22 12:51 UTC by Jenita

Added New table aPeriod and modified timetable procedure and substitute teacher

2023-11-23 06:34 UTC, ArunprasadRajendran requested changes

2023-11-23 06:34 UTC, ArunprasadRajendran commented on server/database/admin/query.ts
> +        const query: any = `INSERT INTO Period( school_id,name,academic_year,start_time,end_time, created_time, created_by,active) VALUES
Pls pull the latest changes from develop branch and use escapeRequestBody method for create and update flow.
refer other flow and follow the same

2023-11-23 06:34 UTC, ArunprasadRajendran commented on server/database/admin/query.ts
> +        });
const stringData: any = JSON.stringify(data, (key: any, value: any) => {
            if (value === null) {
                return;
            }
            return value;
        });
        
use a common method for the code change. refer other stored procedure call

2023-11-23 15:18 UTC, Jenita commented on server/database/admin/query.ts
> +        const query: any = `INSERT INTO Period( school_id,name,academic_year,start_time,end_time, created_time, created_by,active) VALUES
Updated

2023-11-23 15:18 UTC, Jenita commented on server/database/admin/query.ts
> +        });
Updated

2023-11-24 14:42 UTC, ArunprasadRajendran approved these changes

2023-11-25 14:35 UTC, ArunprasadRajendran approved these changes

2023-11-25 14:35 UTC, merged